services:
  bmp:
    image: schowave/bmp:latest
    container_name: bmp
    ports:
      - "8080:8080"
    volumes:
      - ./savegame:/savegame
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"