services:
  bmp:
    image: schowave/bmp:latest
    container_name: bmp
    ports:
      - "8080:80"
    volumes:
      - ./savegame:/savegame
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-bmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup bmp
    restart: unless-stopped
